name       : perl-devel-checklib
version    : '1.16'
release    : 6
source     :
    - https://cpan.metacpan.org/authors/id/M/MA/MATTN/Devel-CheckLib-1.16.tar.gz : 869d38c258e646dcef676609f0dd7ca90f085f56cf6fd7001b019a5d5b831fca
homepage   : https://metacpan.org/pod/Devel::CheckLib
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Devel::CheckLib - check that a library is available
description: |
    Devel::CheckLib is a perl module that checks whether a particular C library and its headers are available.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
