name       : perl-devel-checklib
version    : 1.13
release    : 4
source     :
    - https://cpan.metacpan.org/authors/id/M/MA/MATTN/Devel-CheckLib-1.13.tar.gz : 24adfd908705dfac4bb320711763f37126b75cf54b3566c2c27c7cdef9c429a8
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Check that a library is available
description: |
    Devel::CheckLib is a perl module that checks whether a particular C library and its headers are available.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
